#!/bin/sh

INTERFACE=$1
STATUS=$2
echo "NetworkManager dispatch script: $0 $1 $2"

case "$STATUS" in
    "up")
	exec /etc/rc.d/nfs-common start
	;;
    "down")
	exec /etc/rc.d/nfs-common stop
	;;
esac
